export const data = [
  {
    name: "PLATE [XXX 001]",
    isMining: true,
    timeRemain: 1,
    performance: 1,
    capacity: 10,
    fuel: 20,
  },
  {
    name: "PLATE [XXX 002]",
    isMining: false,
    performance: 1,
    capacity: 10,
    fuel: 100,
  },
  {
    name: "PLATE [XXX 003]",
    isMining: true,
    performance: 1,
    capacity: 150,
    fuel: 100,
  },
  {
    name: "PLATE [XXX 004]",
    isMining: true,
    performance: 1,
    capacity: 0,
    fuel: 0,
  },

  {
    name: "PLATE [XXX 001]",
    isMining: true,
    timeRemain: 1,
    performance: 1,
    capacity: 10,
    fuel: 20,
  },
  {
    name: "PLATE [XXX 002]",
    isMining: false,
    performance: 1,
    capacity: 10,
    fuel: 100,
  },
  {
    name: "PLATE [XXX 003]",
    isMining: true,
    performance: 1,
    capacity: 150,
    fuel: 100,
  },
  {
    name: "PLATE [XXX 004]",
    isMining: true,
    performance: 1,
    capacity: 0,
    fuel: 0,
  },

  {
    name: "PLATE [XXX 001]",
    isMining: true,
    timeRemain: 1,
    performance: 1,
    capacity: 10,
    fuel: 20,
  },
  {
    name: "PLATE [XXX 002]",
    isMining: false,
    performance: 1,
    capacity: 10,
    fuel: 100,
  },
  {
    name: "PLATE [XXX 003]",
    isMining: true,
    performance: 1,
    capacity: 150,
    fuel: 100,
  },
  {
    name: "PLATE [XXX 004]",
    isMining: true,
    performance: 1,
    capacity: 0,
    fuel: 0,
  },

  {
    name: "PLATE [XXX 001]",
    isMining: true,
    timeRemain: 1,
    performance: 1,
    capacity: 10,
    fuel: 20,
  },
  {
    name: "PLATE [XXX 002]",
    isMining: false,
    performance: 1,
    capacity: 10,
    fuel: 100,
  },
  {
    name: "PLATE [XXX 003]",
    isMining: true,
    performance: 1,
    capacity: 150,
    fuel: 100,
  },
  {
    name: "PLATE [XXX 004]",
    isMining: true,
    performance: 1,
    capacity: 0,
    fuel: 0,
  },

  {
    name: "PLATE [XXX 001]",
    isMining: true,
    timeRemain: 1,
    performance: 1,
    capacity: 10,
    fuel: 20,
  },
  {
    name: "PLATE [XXX 002]",
    isMining: false,
    performance: 1,
    capacity: 10,
    fuel: 100,
  },
  {
    name: "PLATE [XXX 003]",
    isMining: true,
    performance: 1,
    capacity: 150,
    fuel: 100,
  },
  {
    name: "PLATE [XXX 004]",
    isMining: true,
    performance: 1,
    capacity: 0,
    fuel: 0,
  },

  {
    name: "PLATE [XXX 001]",
    isMining: true,
    timeRemain: 1,
    performance: 1,
    capacity: 10,
    fuel: 20,
  },
  {
    name: "PLATE [XXX 002]",
    isMining: false,
    performance: 1,
    capacity: 10,
    fuel: 100,
  },
  {
    name: "PLATE [XXX 003]",
    isMining: true,
    performance: 1,
    capacity: 150,
    fuel: 100,
  },
  {
    name: "PLATE [XXX 004]",
    isMining: true,
    performance: 1,
    capacity: 0,
    fuel: 0,
  },
];
